# Generated by Django 5.1.7 on 2025-03-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authy', '0006_alter_woofer_datedenaissance_and_more'),
        ('workshop', '0002_produit_atelier_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payement_type', models.CharField(choices=[('PE', 'PE'), ('PC', 'PC')], default='Espese', max_length=7)),
                ('nomDebiteur', models.CharField(max_length=20, null=True)),
                ('dateExpiration', models.DateField(null=True)),
                ('codeCarte', models.DecimalField(decimal_places=0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('payement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ateliers_produit', to='sales.payement')),
                ('produits', models.ManyToManyField(related_name='ventes_produit', to='workshop.produit')),
                ('woofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ateliers_produit', to='authy.woofer')),
            ],
        ),
        migrations.AddField(
            model_name='payement',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vente_payement', to='sales.vente'),
        ),
    ]
