# Generated by Django 5.1.7 on 2025-03-24 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authy', '0004_woofer_taches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('woofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ateliers', to='authy.woofer')),
            ],
        ),
    ]
