# Generated by Django 5.1.7 on 2025-03-24 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('categorie', models.CharField(choices=[('Oeufs', 'Oeufs'), ('Produit_laitiers', 'Produit_laitiers'), ('Legumes', 'Legumes'), ('Fruits', 'Fruits')], max_length=17)),
            ],
        ),
        migrations.AddField(
            model_name='atelier',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ateliers_produit', to='workshop.produit'),
        ),
    ]
