# Generated by Django 5.1.7 on 2025-03-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_utilisateur_participant_utilisateur_woofer_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woofer',
            name='taches',
            field=models.ManyToManyField(related_name='woofers', to='tasks.tache'),
        ),
    ]
