# Generated by Django 5.1.7 on 2025-03-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_woofer_taches'),
        ('workshop', '0002_produit_atelier_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='ateliers',
            field=models.ManyToManyField(blank=True, related_name='participants', to='workshop.atelier'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_type',
            field=models.CharField(choices=[('Participant', 'Participant'), ('Woofer', 'Woofer'), ('Admin', 'Admin')], default='Participant', max_length=12),
        ),
    ]
