# Generated by Django 5.1.7 on 2025-03-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0005_participant_ateliers_alter_utilisateur_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woofer',
            name='dateDeNaissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='woofer',
            name='dateDebutSejour',
            field=models.DateField(null=True),
        ),
    ]
