# Generated by Django 5.1.7 on 2025-03-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0006_alter_woofer_datedenaissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='woofer',
            name='dateFinSejour',
            field=models.DateField(null=True),
        ),
    ]
